apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: foo-gateway-istio
    version: v1
  name: foo-gateway-istio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo-gateway-istio
      version: v1
  template:
    metadata:
      labels:
        app: foo-gateway-istio
        version: v1
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xms128m -Xmx256m
        image: cloud-workshop/foo-gateway-istio:latest
        imagePullPolicy: IfNotPresent
        name: foo-gateway-istio
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
