apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: foo-service-database-postgres
    version: v1
  name: foo-service-database-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo-service-database-postgres
      version: v1
  template:
    metadata:
      labels:
        app: foo-service-database-postgres
        version: v1
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xms128m -Xmx256m
        image: cloud-workshop/foo-service-database-postgres:latest
        imagePullPolicy: IfNotPresent
        name: foo-service
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
